title: International Press book series CMSA author support
description: TeX related material for the manuscript preparation for the 
             International Press book series Harvard CMSA Series in Mathematics
             (CMSA)
show_downloads: true
theme: jekyll-theme-tactile
